# Generated by Django 5.2.7 on 2025-10-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='stock_maximo',
            field=models.IntegerField(default=100, help_text='Cantidad máxima en stock'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='stock_minimo',
            field=models.IntegerField(default=5, help_text='Cantidad mínima en stock'),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('id_producto', 'ubicacion')},
        ),
    ]
