# Generated by Django 5.2.7 on 2025-11-03 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id_producto_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('precio_acordado', models.IntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
            options={
                'db_table': 'producto_proveedor',
            },
        ),
    ]
