# Generated by Django 5.2.7 on 2025-11-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('contacto', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
