# Generated by Django 5.2.7 on 2025-10-10 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_actual', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=150)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('stock_minimo', models.IntegerField(default=5, help_text='Cantidad mínima en stock')),
                ('stock_maximo', models.IntegerField(default=100, help_text='Cantidad máxima en stock')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'unique_together': {('id_producto', 'ubicacion')},
            },
        ),
    ]
