# Generated by Django 5.2.7 on 2025-10-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('admin', 'Administrador'), ('jefe_ventas', 'Jefe de Ventas'), ('vendedor', 'Vendedor'), ('bodeguero', 'Bodeguero'), ('cliente', 'Cliente'), ('finanzas', 'Finanzas')], default='cliente', max_length=20)),
                ('puede_ver_ventas', models.BooleanField(default=False)),
                ('puede_crear_ventas', models.BooleanField(default=False)),
                ('puede_ver_inventario', models.BooleanField(default=False)),
                ('puede_modificar_inventario', models.BooleanField(default=False)),
                ('puede_ver_clientes', models.BooleanField(default=False)),
                ('puede_crear_clientes', models.BooleanField(default=False)),
                ('puede_ver_proveedores', models.BooleanField(default=False)),
                ('puede_crear_proveedores', models.BooleanField(default=False)),
                ('puede_ver_productos', models.BooleanField(default=False)),
                ('puede_crear_productos', models.BooleanField(default=False)),
                ('puede_ver_usuarios', models.BooleanField(default=False)),
                ('puede_crear_usuarios', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
    ]
