# Generated by Django 5.2.7 on 2025-10-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='puede_aprobar_solicitudes_compra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_crear_solicitudes_compra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_ver_solicitudes_compra',
            field=models.BooleanField(default=False),
        ),
    ]
