# Generated by Django 5.2.7 on 2025-10-12 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_actual', models.IntegerField(verbose_name='Cantidad Actual')),
                ('ubicacion', models.CharField(max_length=150, verbose_name='Ubicación')),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'ordering': ['-fecha_ultima_actualizacion'],
                'unique_together': {('id_producto', 'ubicacion')},
            },
        ),
    ]
