# Generated by Django 5.2.7 on 2025-10-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=150)),
                ('descripcion', models.CharField(help_text='Descripción del producto', max_length=255)),
                ('precio_referencia', models.DecimalField(decimal_places=2, help_text='Precio de referencia del producto', max_digits=10)),
                ('activo', models.BooleanField(default=True, help_text='Si el producto está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
