# Generated by Django 5.2.7 on 2025-10-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='puede_crear_clientes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_crear_productos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_crear_proveedores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_crear_usuarios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_crear_ventas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_modificar_inventario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_ver_clientes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_ver_inventario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_ver_productos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_ver_proveedores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_ver_usuarios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_ver_ventas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('jefe_ventas', 'Jefe de Ventas'), ('vendedor', 'Vendedor'), ('bodeguero', 'Bodeguero'), ('cliente', 'Cliente'), ('finanzas', 'Finanzas')], default='cliente', max_length=20),
        ),
    ]
