# Generated by Django 5.2.7 on 2025-10-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
